### ISSUE TITLE
Support keepalived < 1.3.8 

### ISSUE THREAD

**Issue by fpicot** [cafebazaar/keepalived-exporter#45] opened 2020-08-05 10:23 UTC
The collector use --signum to determine which signal to send to keepalived in order to retrieve stats/data. From keepalived release notes, this parameter has been added in version 1.3.8. 

Unfortunately, the only version available in RHEL 7 and derivatives is 1.3.5. It seems that for this versions, the expected signals are USR1 for data, and USR2 for stats. 

Would it be possible to add a failback to these signals if --signum is not supported ?

**Comment by mehdy** [comment] 2020-08-05 17:37
@fpicot Thanks for the report. we'll consider supporting older versions too. I'll close this one since it's a duplicate of #44.

**Closed by mehdy** 2020-08-05 17:37 UTC
